### ISSUE TITLE
Bug with PrintCenterText?

### ISSUE THREAD

**Issue by Brunes** [Nickelony/Trails-Chroma#1]
Hi, I tested your plugin, maybe I found a bug. After I was set a trail, func PrintCenterText still updating with some number, can you look at it?

Screen here https://ctrlv.cz/shots/2018/01/24/YIZs.png

**Comment by Nickelony** [comment]
Forgot to remove debugging. Will fix in a minute. Thanks for reporting!

**Comment by Nickelony** [comment]
Should be fixed.
