### ISSUE TITLE
Error on playing with Bots - Client X is not in game

### ISSUE THREAD

**Issue by AhRoon** [Nickelony/Trails-Chroma#3]
L 05/05/2019 - 10:58:00: [SM] Exception reported: Client 4 is not in game
L 05/05/2019 - 10:58:00: [SM] Blaming: trails-chroma.smx
L 05/05/2019 - 10:58:00: [SM] Call stack trace:
L 05/05/2019 - 10:58:00: [SM]   [0] GetClientAbsOrigin
L 05/05/2019 - 10:58:00: [SM]   [1] Line 469, C:\Users\Nickelony\Desktop\sourcemod-1.9.0-git6241-windows\addons\sourcemod\scripting\trails-chroma.sp::ForceExpensiveTrails
L 05/05/2019 - 10:58:00: [SM]   [2] Line 435, C:\Users\Nickelony\Desktop\sourcemod-1.9.0-git6241-windows\addons\sourcemod\scripting\trails-chroma.sp::OnPlayerRunCmd

When I'm using this plugin with bot support server, It keeps displays the error. Can you fix this?

**Comment by Nickelony** [comment]
Should be fixed.
