### ISSUE TITLE
Compile issue

### ISSUE THREAD

**Issue by Edward1337M** [Nickelony/Trails-Chroma#4]
plugin.sp(57) : warning 241: Array-based enum structs will be removed in 1.11. See https://wiki.alliedmods.net/SourcePawn_Transitional_Syntax#Enum_Structs
plugin.sp(561) : error 128: cannot return an array of indeterminate length

I am new to sourcepawn, and idk how to fix this this. all i wanted to do is to modify ADMFLAG_RESERVATION to ADMFLAG_CUSTOM6

**Comment by qawery-just-sad** [comment]
i think that you should use `admin_overrides.cfg` in `addons/sourcemod/configs`
and fill it with `"sm_trails_override"   "t"`
