### ISSUE TITLE
Problem with saving trail_choice

### ISSUE THREAD

**Issue by Nevvy** [Nickelony/Trails-Chroma#6]
**Describe the error:**
Hello, I noticed that cookie trail_choice cookie does not save player selection after server restart.
Of course server is restarted when nobody is on it.
Can you investigate it?

**To Reproduce:**
1. Join the server
2. Choose your trail
3. Leave the server
4. Shut down and restart the server
6. Join and your selection the previous selection is not loaded

**Plugin Settings:**
```sm_trails_enable 1
sm_trails_admins_only" 1
sm_trails_allow_hide 1
sm_trails_cheap 0
sm_trails_life 1.5
sm_trails_width 1.5
sm_trails_respawn_disable 0
```

**Plugin Version:**
Latest from this repo: https://github.com/Nickelony/Trails-Chroma/commit/acf660467af13ce2e2c4840401930a0f9c9df46d
**Game: CSGO**

Best regards, Nevvy

**Comment by qawery-just-sad** [comment]
can you check if in your sourcemod db in `sm_cookies` there are `trail_choice` and `trail_hiding` ?
@Nevvy

**Comment by Nevvy** [comment]
`can you check if in your sourcemod db in sm_cookies there are trail_choice and trail_hiding ?`
I have those 2 collums
`is that first time you installed this plugin?`
Yes

I made a video of my steps
https://youtu.be/2lNe7HfMVOI

**Comment by Nickelony** [comment]
I am honestly confused...
Also sorry I wasn't maintaining this plugin, I'm not really a SM dev anymore and I've got other things in life to do. :/

Anyway, I will take a look at the code in a minute.

**Comment by Nickelony** [comment]
Try this first: (though I doubt it would help)
![image](https://user-images.githubusercontent.com/20436882/87910617-939b6400-ca6a-11ea-9af1-a68ec932299e.png)
if it doesn't change anything, try removing this: (highly doubt it would help)
![image](https://user-images.githubusercontent.com/20436882/87910725-c2193f00-ca6a-11ea-9e6a-1d7927a01a62.png)

Other than that, I'm either stupid or there's something wrong on your server. Someone should check my cookies code just to be sure. For me it looks fine, but I might be wrong. ._.

**Comment by Nickelony** [comment]
There's also a chance, that
`bool bNoAccess = gB_AdminsOnly && !CheckCommandAccess(client, "sm_trails_override", ADMFLAG_RESERVATION);
    
if(sChoiceCookie[0] == '\0' || bNoAccess) // If the cookie is empty or the player doesn't have access
{
    IntToString(TRAIL_NONE, sChoiceCookie, 8);
    SetClientCookie(client, gH_TrailChoiceCookie, sChoiceCookie);
}`

executes way too early.
@Nevvy Do you have the gB_AdminsOnly ConVar enabled?

**Comment by Nevvy** [comment]
@Nickelony yes, `sm_trails_admins_only "1"`
I'll try your plugin on my local machine

**Comment by Nevvy** [comment]
After a few tests, I noticed that if `sm_trails_admins_only` = 1 cookie is cleared after shuting down server. Temporary fix set `sm_trails_admins_only` to 0 or replace `OnClientCookiesCached` with `OnClientPostAdminCheck`
After those steps trails works except Spectrum and Wave. They are invisible

**Comment by Nickelony** [comment]
Should possibly be fixed now.
