### ISSUE TITLE
Admin tag?

### ISSUE THREAD

**Issue by AverytheFurry** [Nickelony/Trails-Chroma#7]
What is the default admin tag required for the trails to work and how do you change it?

**Comment by Nickelony** [comment]
**ADMFLAG_RESERVATION** (flag "a") is the default flag used.
If you want to change it, go to `configs/admin_overrides.cfg` and change it using the `sm_trails_override` key.
More info here: https://wiki.alliedmods.net/Overriding_Command_Access_(SourceMod)
