### ISSUE TITLE
Clients Crashing if they don't have server downloads enabled

### ISSUE THREAD

**Issue by ReservedRegister** [Nickelony/Trails-Chroma#8]
Clients crash when they try to load trails for themselves or from other players, only if they have server downloads disabled - meaning they will not get the trail materials

Is it possible to stop the clients from crashing and instead just allow them to play anyway.

My server has this version of your trails plugin:

 13 "Trails Chroma" (2.5) by Nickelony

Plugins runs on Synergy 56.16

**Comment by Nickelony** [comment]
Sorry, this plugin doesn't support SynergyMod. This issue doesn't occur on SourceMod, therefore I can't help you. :/

**Comment by ReservedRegister** [comment]
OK Thanks :)
